# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e2c69d5fc888376d8b25b1a0e438936efb68a16cf4bb29047a19ebeaa9df34ccaf2a6934eb92ee32bbf39d8845455b00d68bb6b5f6a769f5d6136c998c21d8b

test:
  secret_key_base: a87da2af63a64c7ef8b2e5ae495a02a86ed1e03fc538fa71611ee770b9a359a8e98aafe6061d21f865f18f7e73edc90f5eb397b463964c0292d2ef537d279ee8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
